import CombinatorialGames.IGame.Basic
import CombinatorialGames.IGame.IGame
import CombinatorialGames.IGame.Ordinal
import CombinatorialGames.IGame.Special
import CombinatorialGames.Mathlib.AntisymmRel
import CombinatorialGames.Mathlib.CompRel
import CombinatorialGames.Nimber.Basic
import CombinatorialGames.Nimber.Field
